/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "HYUNDAI_RESKILL.h"

unsigned char bAccelPressed = 0;
unsigned char bBreakPressed = 0;


void CPU1_T_1000ms(void);
void CPU1_T_100ms(void);
void CPU1_T_10ms(void);

extern IfxCpu_syncEvent g_cpuSyncEvent;

extern void toggle_red_led(void);
extern void toggle_blue_led(void);
extern void CalculateCarSpeed(void);
extern void ReadSteeringAngle(void);

unsigned int Speed_L = 0;
unsigned int Speed_R = 0;
unsigned int SteeringAngle = 0;


extern unsigned char gInitDone;
int core1_main(void)
{
    unsigned int gCnt = 0;
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    while(1)
    {
        if (gCnt % 10000 == 0)
        {
            CPU1_T_10ms();
        }if (gCnt % 100000 == 0)
        {
            CPU1_T_100ms();
        }if (gCnt % 1000000 == 0)
        {
            CPU1_T_1000ms();
        }
        
        
        gCnt += 1;
    }
    return (1);
}

void CPU1_T_1000ms(void)
{
    if (Speed_L >= 500 && Speed_R >= 500)
    {
        on_red_led(); 
        off_blue_led();
    }
    else if (Speed_L >= 300 && Speed_R >= 300)
    { 
        off_red_led(); 
        on_blue_led();
    }
    else
    {
        off_blue_led();
        off_red_led();
    }
}

void CPU1_T_100ms(void)
{
    ReadSteeringAngle();
    CalculateCarSpeed();
}

void CPU1_T_10ms(void)
{
    if (gInitDone == 1)
    {
        bAccelPressed = read_switch1();
        bBreakPressed = read_switch2();
    }
}

void CalculateCarSpeed(void)
{
    if (bBreakPressed == 1)
    {
        if (Speed_L != 0)
            Speed_L -= 1;
        if (Speed_R != 0)
            Speed_R -= 1;
    }
    if (bAccelPressed == 1)
    {
        if (Speed_L > 1000)
            Speed_L = 1000;
        else
            Speed_L += 1;

        if (Speed_R > 1000)
            Speed_R = 1000;
        else
            Speed_R += 1;
    }
}

void ReadSteeringAngle(void)
{
    unsigned int adc_data = 0;

    if (gInitDone == 1)
    {
        VADC_G4CH7_sampling();
        adc_data = VADC_G4CH7_read();
        /**********************************************************************
         * 
         * Valid range of Variable Register  \  |  /
         *                                   |  |  |
         *                                 0   700  1400
         *                                 |    |    |
         *                                 V    V    V 
         *                                 0    30   60  [degree from center]
         * 
         ***********************************************************************/
        if(adc_data > 1400)
            adc_data = 1400;
        
        SteeringAngle = (((adc_data) * 60) / 1400);
    }
}