/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "HYUNDAI_RESKILL.h"

unsigned int CollisionDistance_CM = 0;
unsigned int CollisionAlert = 0;        // 0: Safe, 1: Distance below 60cm, 2: Distance below 30cm

extern unsigned int range;
extern unsigned char range_valid_flag;
extern IfxCpu_syncEvent g_cpuSyncEvent;

void CPU2_T_1000ms(void);
void CPU2_T_100ms(void);
void CPU2_T_10ms(void);


int core2_main(void)
{
    unsigned int gCnt = 0;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    while(1)
    {
        if (gCnt % 10000 == 0)
        {
            CPU2_T_10ms();
        }
        if (gCnt % 100000 == 0)
        {
            CPU2_T_100ms();
        }
        if (gCnt % 1000000 == 0)
        {
            CPU2_T_1000ms();
        }
        
        gCnt += 1;

        swdelay(10000000);

        // drive TRIG with high (P02.6)
        p02_6_out_set();

        // timer T12 start on CCU60
        ccu60_t12_start();

        // wait until receive ECHO
        while( range_valid_flag == 0);

        CollisionDistance_CM = range;
        if (CollisionDistance_CM < 30) {
            // The distance to the car in front is less than 60 cm.
            CollisionAlert = 2;
        }
        else if (CollisionDistance_CM < 60) {
            // The distance to the car in front is less than 30 cm.
            CollisionAlert = 1;
        }
        else {
            // 
            CollisionAlert = 0;
        }


        // if(        range >= 60) {
        //     on_rgb_red();
        // } else if( range >= 40) {
        //     on_rgb_green();
        // } else if( range >= 20) {
        //     on_rgb_blue();
        // } else {
        //     on_rgb_white();
        // }
    }
    return (1);
}


void CPU2_T_1000ms(void)
{
    toggle_red_led();
}

void CPU2_T_100ms(void)
{
    toggle_blue_led();
}

void CPU2_T_10ms(void)
{
    
}
